# NixOS server management

import '../common.just'

# Deploy NixOS configuration to server
deploy:
    deploy .#hetzner-theor-net-web-1 --remote-build

# Initial server setup with nixos-anywhere
setup:
    ../scripts/provision.sh

# App management CLI
app *args:
    @./scripts/app.sh {{args}}
