# Auto-generated by app.sh - DO NOT EDIT MANUALLY
# This file is generated from apps/*/app.yaml files

{
  cue = {
    image = "ghcr.io/theoryzhenkov/cue/cue:latest";
    containerPort = 3000;
    hostPort = 8102;
    domain = "cue.theor.net";
    depends.database = "postgresql";
    secrets = true;
  };
  home-theor-net = {
    image = "ghcr.io/theoryzhenkov/home.theor.net/home-theor-net:latest";
    containerPort = 80;
    hostPort = 8101;
    domain = "home.theor.net";
  };
  index-theor-net = {
    image = "ghcr.io/theoryzhenkov/index.theor.net/index-theor-net:latest";
    containerPort = 80;
    hostPort = 8100;
    domain = "theor.net";
  };
  private-index-theor-net = {
    image = "ghcr.io/theoryzhenkov/private.index.theor.net/private-index-theor-net:latest";
    containerPort = 80;
    hostPort = 8200;
    domain = "private.theor.net";
    network = "tailscale";
  };
  schedule-theor-net = {
    image = "ghcr.io/theoryzhenkov/schedule.theor.net/schedule-theor-net:latest";
    containerPort = 3000;
    hostPort = 8103;
    domain = "schedule.theor.net";
    secrets = true;
  };
}
