# Auto-generated by app.sh - DO NOT EDIT MANUALLY
# This file is generated from apps/*.yaml files

{
  cue = {
    image = "ghcr.io/theoryzhenkov/cue/cue:latest";
    containerPort = 3000;
    hostPort = 8080;
    domain = "cue.theor.net";
  };
  do-what-you-cant = {
    image = "local/do-what-you-cant:latest";
    containerPort = 8080;
    hostPort = 8127;
    domain = "do-what-you-cant.leaves.theor.net";
  };
  home-theor-net = {
    image = "ghcr.io/theoryzhenkov/home.theor.net/home-theor-net:latest";
    containerPort = 80;
    hostPort = 3000;
    domain = "home.theor.net";
  };
}
