#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
APPS_DIR="$REPO_ROOT/apps"
REMOTE_HOST="${REMOTE_HOST:-hetzner-theor.net-web-1}"
APPS_LOCK_NIX="$APPS_DIR/apps.lock.nix"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[!]${NC} $1" >&2; exit 1; }

# Parse YAML value (simple, no dependencies)
yaml_get() {
    local file="$1" key="$2"
    grep "^${key}:" "$file" 2>/dev/null | sed "s/^${key}:[[:space:]]*//" | tr -d '"'"'"
}

generate_nix_config() {
    log "Generating apps/apps.lock.nix..."
    
    cat > "$APPS_LOCK_NIX" << 'NIXHEAD'
# Auto-generated by app.sh - DO NOT EDIT MANUALLY
# This file is generated from apps/*.yaml files

{
NIXHEAD

    for yaml_file in "$APPS_DIR"/*.yaml; do
        [ -f "$yaml_file" ] || continue
        local name=$(basename "$yaml_file" .yaml)
        local image=$(yaml_get "$yaml_file" "image")
        local domain=$(yaml_get "$yaml_file" "domain")
        local containerPort=$(yaml_get "$yaml_file" "containerPort")
        local hostPort=$(yaml_get "$yaml_file" "hostPort")
        local default_val=$(yaml_get "$yaml_file" "default")
        local database=$(yaml_get "$yaml_file" "database")
        
        [ -n "$image" ] && [ -n "$domain" ] && [ -n "$containerPort" ] && [ -n "$hostPort" ] || continue
        
        local default_line=""
        if [ "$default_val" = "true" ]; then
            default_line=$'\n    default = true;'
        fi

        local database_line=""
        if [ "$database" = "true" ]; then
            database_line=$'\n    database = true;'
        fi

        cat >> "$APPS_LOCK_NIX" << EOF
  ${name} = {
    image = "${image}";
    containerPort = ${containerPort};
    hostPort = ${hostPort};
    domain = "${domain}";${default_line}${database_line}
  };
EOF
    done

    cat >> "$APPS_LOCK_NIX" << 'NIXTAIL'
}
NIXTAIL

    log "Generated $APPS_LOCK_NIX"
}

cmd_create() {
    local name="${1:-}"
    [ -n "$name" ] || error "Usage: just app create <app-name>"
    
    local yaml_file="$APPS_DIR/${name}.yaml"
    [ ! -f "$yaml_file" ] || error "App '$name' already exists at $yaml_file"
    
    log "Creating app config: $name"
    
    # Generate a random port in 8100-8199 range
    local port=$((8100 + RANDOM % 100))
    
    # Default app.yaml  
    cat > "$yaml_file" << EOF
image: ghcr.io/theoryzhenkov/${name}/${name}:latest
containerPort: 8000
hostPort: ${port}
domain: ${name}.theor.net
EOF

    log "Created $yaml_file"
    log "Edit it, then run: just app generate && just deploy"
}

cmd_deploy() {
    local name="${1:-}"
    [ -n "$name" ] || error "Usage: just app deploy <app-name>"
    
    local yaml_file="$APPS_DIR/${name}.yaml"
    [ -f "$yaml_file" ] || error "App '$name' not found at $yaml_file"
    
    local image=$(yaml_get "$yaml_file" "image")
    [ -n "$image" ] || error "No 'image' specified in $yaml_file"
    
    log "Pulling latest image and restarting $name on $REMOTE_HOST..."
    ssh "$REMOTE_HOST" "docker pull ${image} && systemctl restart ${name}"
    log "Deployed $name"
}

cmd_remove() {
    local name="${1:-}"
    [ -n "$name" ] || error "Usage: just app remove <app-name>"
    
    local yaml_file="$APPS_DIR/${name}.yaml"
    
    log "Stopping service on remote..."
    ssh "$REMOTE_HOST" "systemctl stop ${name} || true"
    
    if [ -f "$yaml_file" ]; then
        read -p "Delete app config $yaml_file? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -f "$yaml_file"
            log "Removed $yaml_file"
        fi
    fi
    
    generate_nix_config
    warn "Run 'just deploy' to apply the configuration change"
}

cmd_list() {
    log "Apps:"
    for yaml_file in "$APPS_DIR"/*.yaml; do
        [ -f "$yaml_file" ] || continue
        local name=$(basename "$yaml_file" .yaml)
        local image=$(yaml_get "$yaml_file" "image")
        local domain=$(yaml_get "$yaml_file" "domain")
        local hostPort=$(yaml_get "$yaml_file" "hostPort")
        local database=$(yaml_get "$yaml_file" "database")
        
        local db_tag=""
        [ "$database" = "true" ] && db_tag=" [db]"
        
        echo "  - ${name}${db_tag}"
        echo "      image:   ${image}"
        echo "      domain:  ${domain:-not set}"
        echo "      port:    ${hostPort:-?}"
    done
}

cmd_logs() {
    local name="${1:-}"
    [ -n "$name" ] || error "Usage: just app logs <app-name>"
    
    ssh "$REMOTE_HOST" "journalctl -u ${name} -f"
}

cmd_status() {
    local name="${1:-}"
    if [ -n "$name" ]; then
        ssh "$REMOTE_HOST" "systemctl status ${name}"
    else
        log "Remote app services:"
        local pattern
        pattern=$(for yaml_file in "$APPS_DIR"/*.yaml; do
            [ -f "$yaml_file" ] || continue
            basename "$yaml_file" .yaml
        done | paste -sd '|' -)
        ssh "$REMOTE_HOST" "systemctl list-units --type=service --no-pager | grep -E '(${pattern}|docker-auto-update)' || true"
    fi
}

cmd_generate() {
    generate_nix_config
}

cmd_help() {
    cat << 'EOF'
Usage: just app <command> [args]

Commands:
  create <name>      Create a new app config
  deploy <name>      Pull latest image and restart on server
  remove <name>      Remove app from server (optionally delete config)
  list               List all apps
  logs <name>        Tail logs for an app
  status [name]      Show service status
  generate           Regenerate apps/apps.lock.nix from YAML files

Environment:
  REMOTE_HOST        SSH host (default: hetzner-theor.net-web-1)

Workflow:
  1. just app create myapp     # create apps/myapp.yaml, edit image/domain
  2. just app generate         # update NixOS config
  3. just deploy               # apply NixOS config
  4. just app deploy myapp     # force pull + restart (optional, auto-update runs every 5 min)

Apps are auto-updated every 5 minutes by the docker-auto-update timer.
Check update logs: ssh $REMOTE_HOST 'journalctl -u docker-auto-update'
EOF
}

# Main
case "${1:-help}" in
    create)   cmd_create "${2:-}" ;;
    deploy)   cmd_deploy "${2:-}" ;;
    remove)   cmd_remove "${2:-}" ;;
    list)     cmd_list ;;
    logs)     cmd_logs "${2:-}" ;;
    status)   cmd_status "${2:-}" ;;
    generate) cmd_generate ;;
    help|--help|-h) cmd_help ;;
    *) error "Unknown command: $1. Run 'just app help' for usage." ;;
esac
