#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
APPS_DIR="$REPO_ROOT/apps"
REMOTE_HOST="${REMOTE_HOST:-hetzner-theor.net-web-1}"
APPS_LOCK_NIX="$APPS_DIR/apps.lock.nix"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[!]${NC} $1" >&2; exit 1; }

# Parse YAML value (simple, no dependencies)
yaml_get() {
    local file="$1" key="$2"
    grep "^${key}:" "$file" 2>/dev/null | sed "s/^${key}:[[:space:]]*//" | tr -d '"'"'"
}

# Parse nested YAML value (one level deep, e.g. depends.database)
yaml_get_nested() {
    local file="$1" section="$2" key="$3"
    sed -n "/^${section}:/,/^[^ ]/p" "$file" | grep "^  ${key}:" | sed "s/^  ${key}:[[:space:]]*//" | tr -d '"'"'"
}

# Get canonical app name from YAML (required field)
app_name() {
    local yaml_file="$1"
    local app=$(yaml_get "$yaml_file" "app")
    [ -n "$app" ] || error "Missing required 'app' field in $yaml_file"
    echo "$app"
}

# Resolve app.yaml path from app name
app_yaml() {
    local name="$1"
    echo "$APPS_DIR/${name}/app.yaml"
}

generate_nix_config() {
    log "Generating apps/apps.lock.nix..."
    
    cat > "$APPS_LOCK_NIX" << 'NIXHEAD'
# Auto-generated by app.sh - DO NOT EDIT MANUALLY
# This file is generated from apps/*/app.yaml files

{
NIXHEAD

    for app_dir in "$APPS_DIR"/*/; do
        [ -d "$app_dir" ] || continue
        local yaml_file="${app_dir}app.yaml"
        [ -f "$yaml_file" ] || continue

        local name=$(app_name "$yaml_file")
        local image=$(yaml_get "$yaml_file" "image")
        local domain=$(yaml_get "$yaml_file" "domain")
        local containerPort=$(yaml_get "$yaml_file" "containerPort")
        local hostPort=$(yaml_get "$yaml_file" "hostPort")
        local default_val=$(yaml_get "$yaml_file" "default")
        local depends_database=$(yaml_get_nested "$yaml_file" "depends" "database")
        local network=$(yaml_get "$yaml_file" "network")
        
        [ -n "$image" ] || error "Missing required 'image' field in $yaml_file"
        [ -n "$domain" ] || error "Missing required 'domain' field in $yaml_file"
        [ -n "$containerPort" ] || error "Missing required 'containerPort' field in $yaml_file"
        [ -n "$hostPort" ] || error "Missing required 'hostPort' field in $yaml_file"

        local default_line=""
        if [ "$default_val" = "true" ]; then
            default_line=$'\n    default = true;'
        fi

        local depends_line=""
        if [ -n "$depends_database" ]; then
            depends_line=$'\n    depends.database = "'"${depends_database}"'";'
        fi

        local network_line=""
        if [ -n "$network" ]; then
            network_line=$'\n    network = "'"${network}"'";'
        fi

        # Detect secrets by convention: secrets.enc.yaml exists alongside app.yaml
        local secrets_line=""
        if [ -f "${app_dir}secrets.enc.yaml" ]; then
            secrets_line=$'\n    secrets = true;'
        fi

        cat >> "$APPS_LOCK_NIX" << EOF
  ${name} = {
    image = "${image}";
    containerPort = ${containerPort};
    hostPort = ${hostPort};
    domain = "${domain}";${default_line}${depends_line}${network_line}${secrets_line}
  };
EOF
    done

    cat >> "$APPS_LOCK_NIX" << 'NIXTAIL'
}
NIXTAIL

    log "Generated $APPS_LOCK_NIX"
}

cmd_create() {
    local name="${1:-}"
    [ -n "$name" ] || error "Usage: just app create <app-name>"
    
    local app_dir="$APPS_DIR/${name}"
    local yaml_file="${app_dir}/app.yaml"
    [ ! -f "$yaml_file" ] || error "App '$name' already exists at $yaml_file"
    
    log "Creating app config: $name"
    
    mkdir -p "$app_dir"

    # Generate a random port in 8100-8199 range
    local port=$((8100 + RANDOM % 100))
    
    cat > "$yaml_file" << EOF
app: ${name}
image: ghcr.io/theoryzhenkov/${name}/${name}:latest
containerPort: 8000
hostPort: ${port}
domain: ${name}.theor.net
EOF

    log "Created $yaml_file"
    log "Edit it, then run: just app generate && just deploy"
    log "To add a database: add 'depends:\\n  database: postgresql' to $yaml_file"
    log "To restrict to Tailscale: add 'network: tailscale' to $yaml_file"
    log "To add secrets: just app secrets $name"
}

cmd_deploy() {
    local name="${1:-}"
    [ -n "$name" ] || error "Usage: just app deploy <app-name>"
    
    local yaml_file=$(app_yaml "$name")
    [ -f "$yaml_file" ] || error "App '$name' not found at $yaml_file"
    
    local app=$(app_name "$yaml_file")
    local image=$(yaml_get "$yaml_file" "image")
    [ -n "$image" ] || error "No 'image' specified in $yaml_file"
    
    log "Pulling latest image and restarting $app on $REMOTE_HOST..."
    ssh "$REMOTE_HOST" "docker pull ${image} && systemctl restart ${app}"
    log "Deployed $app"
}

cmd_remove() {
    local name="${1:-}"
    [ -n "$name" ] || error "Usage: just app remove <app-name>"
    
    local yaml_file=$(app_yaml "$name")
    local app=$(app_name "$yaml_file")
    local app_dir="$APPS_DIR/${name}"
    
    log "Stopping service on remote..."
    ssh "$REMOTE_HOST" "systemctl stop ${app} || true"
    
    if [ -d "$app_dir" ]; then
        read -p "Delete app directory $app_dir? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -rf "$app_dir"
            log "Removed $app_dir"
        fi
    fi
    
    generate_nix_config
    warn "Run 'just deploy' to apply the configuration change"
}

cmd_list() {
    log "Apps:"
    for app_dir in "$APPS_DIR"/*/; do
        [ -d "$app_dir" ] || continue
        local yaml_file="${app_dir}app.yaml"
        [ -f "$yaml_file" ] || continue

        local name=$(app_name "$yaml_file")
        local image=$(yaml_get "$yaml_file" "image")
        local domain=$(yaml_get "$yaml_file" "domain")
        local hostPort=$(yaml_get "$yaml_file" "hostPort")
        local depends_database=$(yaml_get_nested "$yaml_file" "depends" "database")
        local network=$(yaml_get "$yaml_file" "network")
        
        local db_tag=""
        [ -n "$depends_database" ] && db_tag=" [db:${depends_database}]"
        local secrets_tag=""
        [ -f "${app_dir}secrets.enc.yaml" ] && secrets_tag=" [secrets]"
        local network_tag=""
        [ -n "$network" ] && network_tag=" [${network}]"
        
        echo "  - ${name}${db_tag}${secrets_tag}${network_tag}"
        echo "      image:   ${image}"
        echo "      domain:  ${domain:-not set}"
        echo "      port:    ${hostPort:-?}"
    done
}

cmd_logs() {
    local name="${1:-}"
    [ -n "$name" ] || error "Usage: just app logs <app-name>"
    
    local yaml_file=$(app_yaml "$name")
    [ -f "$yaml_file" ] || error "App '$name' not found at $yaml_file"
    local app=$(app_name "$yaml_file")
    
    ssh "$REMOTE_HOST" "journalctl -u ${app} -f"
}

cmd_status() {
    local name="${1:-}"
    if [ -n "$name" ]; then
        local yaml_file=$(app_yaml "$name")
        [ -f "$yaml_file" ] || error "App '$name' not found at $yaml_file"
        local app=$(app_name "$yaml_file")
        ssh "$REMOTE_HOST" "systemctl status ${app}"
    else
        log "Remote app services:"
        local pattern
        pattern=$(for app_dir in "$APPS_DIR"/*/; do
            [ -d "$app_dir" ] || continue
            local yaml_file="${app_dir}app.yaml"
            [ -f "$yaml_file" ] || continue
            app_name "$yaml_file"
        done | paste -sd '|' -)
        ssh "$REMOTE_HOST" "systemctl list-units --type=service --no-pager | grep -E '(${pattern}|docker-auto-update)' || true"
    fi
}

cmd_generate() {
    generate_nix_config
}

cmd_secrets() {
    local name="${1:-}"
    [ -n "$name" ] || error "Usage: just app secrets <name>"

    local app_dir="$APPS_DIR/${name}"
    local yaml_file="${app_dir}/app.yaml"
    [ -f "$yaml_file" ] || error "App '$name' not found at $yaml_file"

    local secrets_file="${app_dir}/secrets.enc.yaml"
    sops "$secrets_file"

    log "Secrets updated. Run 'just app generate && just deploy' to apply."
}

cmd_help() {
    cat << 'EOF'
Usage: just app <command> [args]

Commands:
  create <name>          Create a new app config
  deploy <name>          Pull latest image and restart on server
  remove <name>          Remove app from server (optionally delete config)
  list                   List all apps
  logs <name>            Tail logs for an app
  status [name]          Show service status
  generate               Regenerate apps/apps.lock.nix from app configs
  secrets <name>         Edit sops-encrypted secrets for an app

Environment:
  REMOTE_HOST        SSH host (default: hetzner-theor.net-web-1)

Workflow:
  1. just app create myapp     # create apps/myapp/app.yaml, edit image/domain
  2. just app generate         # update NixOS config
  3. just deploy               # apply NixOS config
  4. just app deploy myapp     # force pull + restart (optional, auto-update runs every 5 min)

Dependencies:
  To give an app a PostgreSQL database, add to its app.yaml:
    depends:
      database: postgresql

  The database, user, and password are provisioned automatically.
  DATABASE_URL is injected as an env var at container start.
  No manual secret provisioning required — passwords are derived
  deterministically from the server's age key.

Network:
  To restrict an app to Tailscale peers only, add to its app.yaml:
    network: tailscale

  The app still gets a normal nginx vhost with ACME/TLS, but nginx
  only allows connections from Tailscale IPs (100.64.0.0/10).
  Non-Tailscale clients receive a 403. You still need a DNS record
  pointing the domain to the server's public IP (for ACME to work).

Secrets:
  Secrets are sops-encrypted files in the infra repo at apps/<name>/secrets.enc.yaml.
  They are decrypted on the server at service start using the server's Age key.

  1. just app secrets myapp    # create/edit encrypted secrets (flat YAML key-value pairs)
  2. just app generate         # regenerate lock file (detects secrets.enc.yaml)
  3. just deploy               # deploy with secrets

  App repos don't handle secrets — they just declare what env vars they expect.
  Secret values live here in the infra repo.

Apps are auto-updated every 5 minutes by the docker-auto-update timer.
Image updates trigger restarts. Secrets changes require a deploy.
Check update logs: ssh $REMOTE_HOST 'journalctl -u docker-auto-update'
EOF
}

# Main
case "${1:-help}" in
    create)        cmd_create "${2:-}" ;;
    deploy)        cmd_deploy "${2:-}" ;;
    remove)        cmd_remove "${2:-}" ;;
    list)          cmd_list ;;
    logs)          cmd_logs "${2:-}" ;;
    status)        cmd_status "${2:-}" ;;
    generate)      cmd_generate ;;
    secrets)       cmd_secrets "${2:-}" ;;
    help|--help|-h) cmd_help ;;
    *) error "Unknown command: $1. Run 'just app help' for usage." ;;
esac
